TYPO3:
  Flow:
    security:
      firewall:
        filters:
          -
            patternType: 'URI'
            patternValue: '/i/.*'
            interceptor: 'Ttree\Identicons\Authorization\Interceptor\FloodMitigation'

Ttree:
  Identicons:
    persist: TRUE
    size: 420
    background:
      color: '#FFF'
      opacity: 100
    ttl: 2592000
    access:
      enable: FALSE
    flood:
      enable: TRUE
      limit: 30
    generator:
      'Ttree\Identicons\Generator\DonParkGenerator':
        sprite:
          default: [0, 0, 1, 0, 0.5, 0.5, 0.5, 0, 0, 0.5, 1, 0.5, 0.5, 1, 0.5, 0.5, 0, 1]
          shapes:
            - [0.5, 1, 1, 0, 1, 1]
            - [0.5, 0, 1, 0, 0.5, 1, 0, 1]
            - [0.5, 0, 1, 0, 1, 1, 0.5, 1, 1, 0.5]
            - [0, 0.5, 0.5, 0, 1, 0.5, 0.5, 1, 0.5, 0.5]
            - [0, 0.5, 1, 0, 1, 1, 0, 1, 1, 0.5]
            - [1, 0, 1, 1, 0.5, 1, 1, 0.5, 0.5, 0.5]
            - [0, 0, 1, 0, 1, 0.5, 0, 0, 0.5, 1, 0, 1]
            - [0, 0, 0.5, 0, 1, 0.5, 0.5, 1, 0, 1, 0.5, 0.5]
            - [0.5, 0, 0.5, 0.5, 1, 0.5, 1, 1, 0.5, 1, 0.5, 0.5, 0, 0.5]
            - [0, 0, 1, 0, 0.5, 0.5, 1, 0.5, 0.5, 1, 0.5, 0.5, 0, 1]
            - [0, 0.5, 0.5, 1, 1, 0.5, 0.5, 0, 1, 0, 1, 1, 0, 1]
            - [0.5, 0, 1, 0, 1, 1, 0.5, 1, 1, 0.75, 0.5, 0.5, 1, 0.25]
            - [0, 0.5, 0.5, 0, 0.5, 0.5, 1, 0, 1, 0.5, 0.5, 1, 0.5, 0.5, 0, 1]
            - [0, 0, 1, 0, 1, 1, 0, 1, 1, 0.5, 0.5, 0.25, 0.5, 0.75, 0, 0.5, 0.5, 0.25]
            - [0, 0.5, 0.5, 0.5, 0.5, 0, 1, 0, 0.5, 0.5, 1, 0.5, 0.5, 1, 0.5, 0.5, 0, 1]
        centerSprite:
          default: []
          shapes:
            - []
            - [0, 0, 1, 0, 1, 1, 0, 1]
            - [0.5, 0, 1, 0.5, 0.5, 1, 0, 0.5]
            - [0, 0, 1, 0, 1, 1, 0, 1, 0, 0.5, 0.5, 1, 1, 0.5, 0.5, 0, 0, 0.5]
            - [0.25, 0, 0.75, 0, 0.5, 0.5, 1, 0.25, 1, 0.75, 0.5, 0.5, 0.75, 1, 0.25, 1, 0.5, 0.5, 0, 0.75, 0, 0.25, 0.5, 0.5]
            - [0, 0, 0.5, 0.25, 1, 0, 0.75, 0.5, 1, 1, 0.5, 0.75, 0, 1, 0.25, 0.5]
            - [0.33, 0.33, 0.67, 0.33, 0.67, 0.67, 0.33, 0.67]
            - [0, 0, 0.33, 0, 0.33, 0.33, 0.66, 0.33, 0.67, 0, 1, 0, 1, 0.33, 0.67, 0.33, 0.67, 0.67, 1, 0.67, 1, 1, 0.67, 1, 0.67, 0.67, 0.33, 0.67, 0.33, 1, 0, 1, 0, 0.67, 0.33, 0.67, 0.33, 0.33, 0, 0.33]

      'Ttree\Identicons\Generator\GithubLikeGenerator':
        squareSprite:
          default: [0, 0, 0, 1]
          shapes:
            - [0, 0, 1, 1]
            - [0, 1, 1, 1]
            - [0, 1, 0, 1]
            - [1, 1, 0, 0]
            - [1, 1, 1, 0]
            - [1, 0, 1, 1]
            - [1, 0, 0, 1]
            - [0, 1, 1, 0]
            - [0, 1, 0, 0]
            - [1, 0, 0, 0]
            - [1, 0, 1, 0]
            - [1, 1, 0, 1]
        rectangularSprite:
          default: [1, 1]
          shapes:
            - [0, 0]
            - [1, 1]
            - [0, 1]
            - [1, 0]
