TYPO3:
  Flow:
    security:
      firewall:
        filters:
          -
            patternType: 'URI'
            patternValue: '/i/.*'
            interceptor: 'Ttree\Identicons\Authorization\Interceptor\FloodMitigation'

Ttree:
  Identicons:
    persist: TRUE
    size: 420
    background:
      color: '#FFF'
      opacity: 100
    ttl: 2592000
    access:
      enable: FALSE
    flood:
      enable: TRUE
      limit: 30
    generator:
      'Ttree\Identicons\Generator\GithubLikeGenerator':
        squareSprite:
          default: [0, 0, 0, 1]
          shapes:
            - [0, 0, 1, 1]
            - [0, 1, 1, 1]
            - [0, 1, 0, 1]
            - [1, 1, 0, 0]
            - [1, 1, 1, 0]
            - [1, 0, 1, 1]
            - [1, 0, 0, 1]
            - [0, 1, 1, 0]
            - [0, 1, 0, 0]
            - [1, 0, 0, 0]
            - [1, 0, 1, 0]
            - [1, 1, 0, 1]
        rectangularSprite:
          default: [1, 1]
          shapes:
            - [0, 0]
            - [1, 1]
            - [0, 1]
            - [1, 0]
