TYPO3:
  Flow:
    security:
      firewall:
        filters:
          -
            patternType: 'URI'
            patternValue: '/i/.*'
            interceptor: 'Ttree\Identicons\Authorization\Interceptor\FloodMitigation'

Ttree:
  Identicons:
    persist: TRUE
    size: 420
    backgroundColor: '#EEE'
    ttl: 2592000
    access:
      enable: FALSE
    flood:
      enable: TRUE
      limit: 30